set(_CATKIN_CURRENT_PACKAGE "sbpl_lattice_planner")
set(sbpl_lattice_planner_VERSION "0.2.0")
set(sbpl_lattice_planner_MAINTAINER "Martin Günther <martin.guenther@dfki.de>")
set(sbpl_lattice_planner_PACKAGE_FORMAT "2")
set(sbpl_lattice_planner_BUILD_DEPENDS "message_generation" "costmap_2d" "geometry_msgs" "nav_core" "nav_msgs" "pluginlib" "roscpp" "sbpl" "tf2")
set(sbpl_lattice_planner_BUILD_EXPORT_DEPENDS "costmap_2d" "geometry_msgs" "nav_core" "nav_msgs" "pluginlib" "roscpp" "sbpl" "tf2")
set(sbpl_lattice_planner_BUILDTOOL_DEPENDS "catkin")
set(sbpl_lattice_planner_BUILDTOOL_EXPORT_DEPENDS )
set(sbpl_lattice_planner_EXEC_DEPENDS "message_runtime" "costmap_2d" "geometry_msgs" "nav_core" "nav_msgs" "pluginlib" "roscpp" "sbpl" "tf2")
set(sbpl_lattice_planner_RUN_DEPENDS "message_runtime" "costmap_2d" "geometry_msgs" "nav_core" "nav_msgs" "pluginlib" "roscpp" "sbpl" "tf2")
set(sbpl_lattice_planner_TEST_DEPENDS )
set(sbpl_lattice_planner_DOC_DEPENDS )
set(sbpl_lattice_planner_URL_WEBSITE "http://wiki.ros.org/sbpl_lattice_planner")
set(sbpl_lattice_planner_URL_BUGTRACKER "https://github.com/ros-planning/navigation_experimental/issues")
set(sbpl_lattice_planner_URL_REPOSITORY "https://github.com/ros-planning/navigation_experimental.git")
set(sbpl_lattice_planner_DEPRECATED "")