set(_CATKIN_CURRENT_PACKAGE "multi_robot_exploration")
set(multi_robot_exploration_VERSION "0.0.0")
set(multi_robot_exploration_MAINTAINER "tharushi <tharushi@todo.todo>")
set(multi_robot_exploration_PACKAGE_FORMAT "2")
set(multi_robot_exploration_BUILD_DEPENDS )
set(multi_robot_exploration_BUILD_EXPORT_DEPENDS )
set(multi_robot_exploration_BUILDTOOL_DEPENDS "catkin")
set(multi_robot_exploration_BUILDTOOL_EXPORT_DEPENDS )
set(multi_robot_exploration_EXEC_DEPENDS )
set(multi_robot_exploration_RUN_DEPENDS )
set(multi_robot_exploration_TEST_DEPENDS )
set(multi_robot_exploration_DOC_DEPENDS )
set(multi_robot_exploration_URL_WEBSITE "")
set(multi_robot_exploration_URL_BUGTRACKER "")
set(multi_robot_exploration_URL_REPOSITORY "")
set(multi_robot_exploration_DEPRECATED "")