set(_CATKIN_CURRENT_PACKAGE "navigation_experimental")
set(navigation_experimental_VERSION "0.2.0")
set(navigation_experimental_MAINTAINER "Martin Günther <martin.guenther@dfki.de>")
set(navigation_experimental_PACKAGE_FORMAT "2")
set(navigation_experimental_BUILD_DEPENDS )
set(navigation_experimental_BUILD_EXPORT_DEPENDS )
set(navigation_experimental_BUILDTOOL_DEPENDS "catkin")
set(navigation_experimental_BUILDTOOL_EXPORT_DEPENDS )
set(navigation_experimental_EXEC_DEPENDS "assisted_teleop" "goal_passer" "pose_base_controller" "pose_follower" "sbpl_lattice_planner" "sbpl_recovery" "twist_recovery")
set(navigation_experimental_RUN_DEPENDS "assisted_teleop" "goal_passer" "pose_base_controller" "pose_follower" "sbpl_lattice_planner" "sbpl_recovery" "twist_recovery")
set(navigation_experimental_TEST_DEPENDS )
set(navigation_experimental_DOC_DEPENDS )
set(navigation_experimental_URL_WEBSITE "http://wiki.ros.org/navigation_experimental")
set(navigation_experimental_URL_BUGTRACKER "https://github.com/ros-planning/navigation_experimental/issues")
set(navigation_experimental_URL_REPOSITORY "https://github.com/ros-planning/navigation_experimental.git")
set(navigation_experimental_DEPRECATED "")