set(_CATKIN_CURRENT_PACKAGE "pose_merge")
set(pose_merge_VERSION "0.0.0")
set(pose_merge_MAINTAINER "tharushi <tharushi@todo.todo>")
set(pose_merge_PACKAGE_FORMAT "2")
set(pose_merge_BUILD_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "geometry_msgs" "libpcl-all-dev" "octomap_msgs" "octomap_ros" "octomap")
set(pose_merge_BUILD_EXPORT_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "geometry_msgs" "octomap_msgs" "octomap_ros")
set(pose_merge_BUILDTOOL_DEPENDS "catkin")
set(pose_merge_BUILDTOOL_EXPORT_DEPENDS )
set(pose_merge_EXEC_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "geometry_msgs" "libpcl-all" "octomap_msgs" "octomap" "octomap_ros")
set(pose_merge_RUN_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "geometry_msgs" "libpcl-all" "octomap_msgs" "octomap" "octomap_ros")
set(pose_merge_TEST_DEPENDS )
set(pose_merge_DOC_DEPENDS )
set(pose_merge_URL_WEBSITE "")
set(pose_merge_URL_BUGTRACKER "")
set(pose_merge_URL_REPOSITORY "")
set(pose_merge_DEPRECATED "")