# CMake generated Testfile for 
# Source directory: /home/kalana/Xavier/Robot/src/rgbd_launch
# Build directory: /home/kalana/Xavier/Robot/build_isolated/rgbd_launch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rgbd_launch_roslaunch-check_launch "/home/kalana/Xavier/Robot/build_isolated/rgbd_launch/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kalana/Xavier/Robot/build_isolated/rgbd_launch/test_results/rgbd_launch/roslaunch-check_launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/kalana/Xavier/Robot/build_isolated/rgbd_launch/test_results/rgbd_launch" "/opt/ros/kinetic/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/kalana/Xavier/Robot/build_isolated/rgbd_launch/test_results/rgbd_launch/roslaunch-check_launch.xml' '/home/kalana/Xavier/Robot/src/rgbd_launch/launch' ")
add_test(_ctest_rgbd_launch_roslaunch-check_test "/home/kalana/Xavier/Robot/build_isolated/rgbd_launch/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kalana/Xavier/Robot/build_isolated/rgbd_launch/test_results/rgbd_launch/roslaunch-check_test.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/kalana/Xavier/Robot/build_isolated/rgbd_launch/test_results/rgbd_launch" "/opt/ros/kinetic/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/kalana/Xavier/Robot/build_isolated/rgbd_launch/test_results/rgbd_launch/roslaunch-check_test.xml' '/home/kalana/Xavier/Robot/src/rgbd_launch/test' ")
add_test(_ctest_rgbd_launch_rostest_test_camera.test "/home/kalana/Xavier/Robot/build_isolated/rgbd_launch/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kalana/Xavier/Robot/build_isolated/rgbd_launch/test_results/rgbd_launch/rostest-test_camera.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/kalana/Xavier/Robot/src/rgbd_launch --package=rgbd_launch --results-filename test_camera.xml --results-base-dir \"/home/kalana/Xavier/Robot/build_isolated/rgbd_launch/test_results\" /home/kalana/Xavier/Robot/src/rgbd_launch/test/camera.test ")
subdirs(gtest)
