set(_CATKIN_CURRENT_PACKAGE "pose_base_controller")
set(pose_base_controller_VERSION "0.2.0")
set(pose_base_controller_MAINTAINER "Martin Günther <martin.guenther@dfki.de>")
set(pose_base_controller_PACKAGE_FORMAT "2")
set(pose_base_controller_BUILD_DEPENDS "actionlib" "geometry_msgs" "move_base_msgs" "nav_msgs" "roscpp" "tf")
set(pose_base_controller_BUILD_EXPORT_DEPENDS "actionlib" "geometry_msgs" "move_base_msgs" "nav_msgs" "roscpp" "tf")
set(pose_base_controller_BUILDTOOL_DEPENDS "catkin")
set(pose_base_controller_BUILDTOOL_EXPORT_DEPENDS )
set(pose_base_controller_EXEC_DEPENDS "actionlib" "geometry_msgs" "move_base_msgs" "nav_msgs" "roscpp" "tf")
set(pose_base_controller_RUN_DEPENDS "actionlib" "geometry_msgs" "move_base_msgs" "nav_msgs" "roscpp" "tf")
set(pose_base_controller_TEST_DEPENDS )
set(pose_base_controller_DOC_DEPENDS )
set(pose_base_controller_URL_WEBSITE "http://wiki.ros.org/pose_base_controller")
set(pose_base_controller_URL_BUGTRACKER "https://github.com/ros-planning/navigation_experimental/issues")
set(pose_base_controller_URL_REPOSITORY "https://github.com/ros-planning/navigation_experimental.git")
set(pose_base_controller_DEPRECATED "")