set(_CATKIN_CURRENT_PACKAGE "node_manager_fkie")
set(node_manager_fkie_VERSION "0.8.9")
set(node_manager_fkie_MAINTAINER "Alexander Tiderko <alexander.tiderko@gmail.com>")
set(node_manager_fkie_PACKAGE_FORMAT "1")
set(node_manager_fkie_BUILD_DEPENDS "multimaster_msgs_fkie" "master_discovery_fkie" "diagnostic_msgs")
set(node_manager_fkie_BUILD_EXPORT_DEPENDS "multimaster_msgs_fkie" "master_discovery_fkie" "master_sync_fkie" "default_cfg_fkie" "rospy" "roslib" "rosmsg" "rosgraph" "roslaunch" "rosservice" "dynamic_reconfigure" "rqt_reconfigure" "diagnostic_msgs" "python_qt_binding" "python-paramiko" "python-docutils" "screen" "xterm" "rqt_gui")
set(node_manager_fkie_BUILDTOOL_DEPENDS "catkin")
set(node_manager_fkie_BUILDTOOL_EXPORT_DEPENDS )
set(node_manager_fkie_EXEC_DEPENDS "multimaster_msgs_fkie" "master_discovery_fkie" "master_sync_fkie" "default_cfg_fkie" "rospy" "roslib" "rosmsg" "rosgraph" "roslaunch" "rosservice" "dynamic_reconfigure" "rqt_reconfigure" "diagnostic_msgs" "python_qt_binding" "python-paramiko" "python-docutils" "screen" "xterm" "rqt_gui")
set(node_manager_fkie_RUN_DEPENDS "multimaster_msgs_fkie" "master_discovery_fkie" "master_sync_fkie" "default_cfg_fkie" "rospy" "roslib" "rosmsg" "rosgraph" "roslaunch" "rosservice" "dynamic_reconfigure" "rqt_reconfigure" "diagnostic_msgs" "python_qt_binding" "python-paramiko" "python-docutils" "screen" "xterm" "rqt_gui")
set(node_manager_fkie_TEST_DEPENDS )
set(node_manager_fkie_DOC_DEPENDS )
set(node_manager_fkie_URL_WEBSITE "http://ros.org/wiki/node_manager_fkie")
set(node_manager_fkie_URL_BUGTRACKER "")
set(node_manager_fkie_URL_REPOSITORY "")
set(node_manager_fkie_DEPRECATED "")