set(node_manager_fkie_SETUP_PY_VERSION "0.8.9")
set(node_manager_fkie_SETUP_PY_SCRIPTS "nodes/node_manager")
set(node_manager_fkie_SETUP_PY_PACKAGES "node_manager_fkie")
set(node_manager_fkie_SETUP_PY_PACKAGE_DIRS "src/node_manager_fkie")
set(node_manager_fkie_SETUP_PY_MODULES "")
set(node_manager_fkie_SETUP_PY_MODULE_DIRS "")