set(_CATKIN_CURRENT_PACKAGE "icp_merge")
set(icp_merge_VERSION "0.0.0")
set(icp_merge_MAINTAINER "tharushi <tharushid.14@cse.mrt.ac.lk>")
set(icp_merge_PACKAGE_FORMAT "2")
set(icp_merge_BUILD_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "geometry_msgs" "libpcl-all-dev" "octomap_msgs" "octomap_ros" "libpcl-all-dev" "octomap")
set(icp_merge_BUILD_EXPORT_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "geometry_msgs" "octomap_msgs" "octomap_ros")
set(icp_merge_BUILDTOOL_DEPENDS "catkin")
set(icp_merge_BUILDTOOL_EXPORT_DEPENDS )
set(icp_merge_EXEC_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "geometry_msgs" "libpcl-all" "octomap_msgs" "octomap" "octomap_ros" "libpcl-all")
set(icp_merge_RUN_DEPENDS "pcl_conversions" "pcl_ros" "roscpp" "sensor_msgs" "geometry_msgs" "libpcl-all" "octomap_msgs" "octomap" "octomap_ros")
set(icp_merge_TEST_DEPENDS )
set(icp_merge_DOC_DEPENDS )
set(icp_merge_URL_WEBSITE "")
set(icp_merge_URL_BUGTRACKER "")
set(icp_merge_URL_REPOSITORY "")
set(icp_merge_DEPRECATED "")