set(_CATKIN_CURRENT_PACKAGE "default_cfg_fkie")
set(default_cfg_fkie_VERSION "0.8.9")
set(default_cfg_fkie_MAINTAINER "Alexander Tiderko <alexander.tiderko@gmail.com>")
set(default_cfg_fkie_PACKAGE_FORMAT "1")
set(default_cfg_fkie_BUILD_DEPENDS "multimaster_msgs_fkie")
set(default_cfg_fkie_BUILD_EXPORT_DEPENDS "multimaster_msgs_fkie" "rospy" "roslib" "roslaunch")
set(default_cfg_fkie_BUILDTOOL_DEPENDS "catkin")
set(default_cfg_fkie_BUILDTOOL_EXPORT_DEPENDS )
set(default_cfg_fkie_EXEC_DEPENDS "multimaster_msgs_fkie" "rospy" "roslib" "roslaunch")
set(default_cfg_fkie_RUN_DEPENDS "multimaster_msgs_fkie" "rospy" "roslib" "roslaunch")
set(default_cfg_fkie_TEST_DEPENDS )
set(default_cfg_fkie_DOC_DEPENDS )
set(default_cfg_fkie_URL_WEBSITE "http://ros.org/wiki/default_cfg_fkie")
set(default_cfg_fkie_URL_BUGTRACKER "")
set(default_cfg_fkie_URL_REPOSITORY "")
set(default_cfg_fkie_DEPRECATED "")