# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/BumperEvent.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/CliffEvent.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/DigitalOutput.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/ExternalPower.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/Led.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/PowerSystemEvent.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/SensorState.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/VersionInfo.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/ControllerInfo.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/ButtonEvent.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/DigitalInputEvent.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/DockInfraRed.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/KeyboardInput.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/MotorPower.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/RobotStateEvent.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/Sound.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/ScanAngle.msg;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg/WheelDropEvent.msg;/home/kalana/Xavier/Robot/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg/AutoDockingAction.msg;/home/kalana/Xavier/Robot/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg/AutoDockingActionGoal.msg;/home/kalana/Xavier/Robot/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg/AutoDockingActionResult.msg;/home/kalana/Xavier/Robot/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg/AutoDockingActionFeedback.msg;/home/kalana/Xavier/Robot/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg/AutoDockingGoal.msg;/home/kalana/Xavier/Robot/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg/AutoDockingResult.msg;/home/kalana/Xavier/Robot/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg/AutoDockingFeedback.msg"
services_str = ""
pkg_name = "kobuki_msgs"
dependencies_str = "std_msgs;actionlib_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "kobuki_msgs;/home/kalana/Xavier/Robot/src/kobuki/kobuki_msgs-kinetic/msg;kobuki_msgs;/home/kalana/Xavier/Robot/devel_isolated/kobuki_msgs/share/kobuki_msgs/msg;std_msgs;/opt/ros/kinetic/share/std_msgs/cmake/../msg;actionlib_msgs;/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python2"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/kinetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
