set(_CATKIN_CURRENT_PACKAGE "master_sync_fkie")
set(master_sync_fkie_VERSION "0.8.9")
set(master_sync_fkie_MAINTAINER "Alexander Tiderko <alexander.tiderko@gmail.com>")
set(master_sync_fkie_PACKAGE_FORMAT "1")
set(master_sync_fkie_BUILD_DEPENDS "multimaster_msgs_fkie" "master_discovery_fkie")
set(master_sync_fkie_BUILD_EXPORT_DEPENDS "rospy" "roslib" "rosgraph" "multimaster_msgs_fkie" "master_discovery_fkie")
set(master_sync_fkie_BUILDTOOL_DEPENDS "catkin")
set(master_sync_fkie_BUILDTOOL_EXPORT_DEPENDS )
set(master_sync_fkie_EXEC_DEPENDS "rospy" "roslib" "rosgraph" "multimaster_msgs_fkie" "master_discovery_fkie")
set(master_sync_fkie_RUN_DEPENDS "rospy" "roslib" "rosgraph" "multimaster_msgs_fkie" "master_discovery_fkie")
set(master_sync_fkie_TEST_DEPENDS )
set(master_sync_fkie_DOC_DEPENDS )
set(master_sync_fkie_URL_WEBSITE "http://ros.org/wiki/master_sync_fkie")
set(master_sync_fkie_URL_BUGTRACKER "")
set(master_sync_fkie_URL_REPOSITORY "")
set(master_sync_fkie_DEPRECATED "")