set(_CATKIN_CURRENT_PACKAGE "my_robot_config")
set(my_robot_config_VERSION "0.0.0")
set(my_robot_config_MAINTAINER "imesh <imesh@todo.todo>")
set(my_robot_config_PACKAGE_FORMAT "2")
set(my_robot_config_BUILD_DEPENDS )
set(my_robot_config_BUILD_EXPORT_DEPENDS )
set(my_robot_config_BUILDTOOL_DEPENDS "catkin")
set(my_robot_config_BUILDTOOL_EXPORT_DEPENDS )
set(my_robot_config_EXEC_DEPENDS )
set(my_robot_config_RUN_DEPENDS )
set(my_robot_config_TEST_DEPENDS )
set(my_robot_config_DOC_DEPENDS )
set(my_robot_config_URL_WEBSITE "")
set(my_robot_config_URL_BUGTRACKER "")
set(my_robot_config_URL_REPOSITORY "")
set(my_robot_config_DEPRECATED "")