set(_CATKIN_CURRENT_PACKAGE "multimaster_fkie")
set(multimaster_fkie_VERSION "0.8.9")
set(multimaster_fkie_MAINTAINER "Alexander Tiderko <alexander.tiderko@gmail.com>")
set(multimaster_fkie_PACKAGE_FORMAT "1")
set(multimaster_fkie_BUILD_DEPENDS )
set(multimaster_fkie_BUILD_EXPORT_DEPENDS "multimaster_msgs_fkie" "default_cfg_fkie" "master_discovery_fkie" "master_sync_fkie" "node_manager_fkie")
set(multimaster_fkie_BUILDTOOL_DEPENDS "catkin")
set(multimaster_fkie_BUILDTOOL_EXPORT_DEPENDS )
set(multimaster_fkie_EXEC_DEPENDS "multimaster_msgs_fkie" "default_cfg_fkie" "master_discovery_fkie" "master_sync_fkie" "node_manager_fkie")
set(multimaster_fkie_RUN_DEPENDS "multimaster_msgs_fkie" "default_cfg_fkie" "master_discovery_fkie" "master_sync_fkie" "node_manager_fkie")
set(multimaster_fkie_TEST_DEPENDS )
set(multimaster_fkie_DOC_DEPENDS )
set(multimaster_fkie_URL_WEBSITE "http://ros.org/wiki/multimaster_fkie")
set(multimaster_fkie_URL_BUGTRACKER "")
set(multimaster_fkie_URL_REPOSITORY "")
set(multimaster_fkie_DEPRECATED "")