# CMake generated Testfile for 
# Source directory: /home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl
# Build directory: /home/kalana/Xavier/Robot/build_isolated/amcl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_amcl_rostest_test_set_initial_pose.xml "/home/kalana/Xavier/Robot/build_isolated/amcl/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kalana/Xavier/Robot/build_isolated/amcl/test_results/amcl/rostest-test_set_initial_pose.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl --package=amcl --results-filename test_set_initial_pose.xml --results-base-dir \"/home/kalana/Xavier/Robot/build_isolated/amcl/test_results\" /home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl/test/set_initial_pose.xml ")
add_test(_ctest_amcl_rostest_test_set_initial_pose_delayed.xml "/home/kalana/Xavier/Robot/build_isolated/amcl/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kalana/Xavier/Robot/build_isolated/amcl/test_results/amcl/rostest-test_set_initial_pose_delayed.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl --package=amcl --results-filename test_set_initial_pose_delayed.xml --results-base-dir \"/home/kalana/Xavier/Robot/build_isolated/amcl/test_results\" /home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl/test/set_initial_pose_delayed.xml ")
add_test(_ctest_amcl_rostest_test_basic_localization_stage.xml "/home/kalana/Xavier/Robot/build_isolated/amcl/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kalana/Xavier/Robot/build_isolated/amcl/test_results/amcl/rostest-test_basic_localization_stage.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl --package=amcl --results-filename test_basic_localization_stage.xml --results-base-dir \"/home/kalana/Xavier/Robot/build_isolated/amcl/test_results\" /home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl/test/basic_localization_stage.xml ")
add_test(_ctest_amcl_rostest_test_small_loop_prf.xml "/home/kalana/Xavier/Robot/build_isolated/amcl/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kalana/Xavier/Robot/build_isolated/amcl/test_results/amcl/rostest-test_small_loop_prf.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl --package=amcl --results-filename test_small_loop_prf.xml --results-base-dir \"/home/kalana/Xavier/Robot/build_isolated/amcl/test_results\" /home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl/test/small_loop_prf.xml ")
add_test(_ctest_amcl_rostest_test_small_loop_crazy_driving_prg.xml "/home/kalana/Xavier/Robot/build_isolated/amcl/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kalana/Xavier/Robot/build_isolated/amcl/test_results/amcl/rostest-test_small_loop_crazy_driving_prg.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl --package=amcl --results-filename test_small_loop_crazy_driving_prg.xml --results-base-dir \"/home/kalana/Xavier/Robot/build_isolated/amcl/test_results\" /home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl/test/small_loop_crazy_driving_prg.xml ")
add_test(_ctest_amcl_rostest_test_texas_greenroom_loop.xml "/home/kalana/Xavier/Robot/build_isolated/amcl/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kalana/Xavier/Robot/build_isolated/amcl/test_results/amcl/rostest-test_texas_greenroom_loop.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl --package=amcl --results-filename test_texas_greenroom_loop.xml --results-base-dir \"/home/kalana/Xavier/Robot/build_isolated/amcl/test_results\" /home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl/test/texas_greenroom_loop.xml ")
add_test(_ctest_amcl_rostest_test_rosie_multilaser.xml "/home/kalana/Xavier/Robot/build_isolated/amcl/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kalana/Xavier/Robot/build_isolated/amcl/test_results/amcl/rostest-test_rosie_multilaser.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl --package=amcl --results-filename test_rosie_multilaser.xml --results-base-dir \"/home/kalana/Xavier/Robot/build_isolated/amcl/test_results\" /home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl/test/rosie_multilaser.xml ")
add_test(_ctest_amcl_rostest_test_texas_willow_hallway_loop.xml "/home/kalana/Xavier/Robot/build_isolated/amcl/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kalana/Xavier/Robot/build_isolated/amcl/test_results/amcl/rostest-test_texas_willow_hallway_loop.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl --package=amcl --results-filename test_texas_willow_hallway_loop.xml --results-base-dir \"/home/kalana/Xavier/Robot/build_isolated/amcl/test_results\" /home/kalana/Xavier/Robot/src/Navigation/navigation-kinetic-devel/amcl/test/texas_willow_hallway_loop.xml ")
subdirs(gtest)
