set(_CATKIN_CURRENT_PACKAGE "testworld_gazebo")
set(testworld_gazebo_VERSION "0.0.0")
set(testworld_gazebo_MAINTAINER "kalana <kalana@todo.todo>")
set(testworld_gazebo_PACKAGE_FORMAT "2")
set(testworld_gazebo_BUILD_DEPENDS "roscpp" "rospy")
set(testworld_gazebo_BUILD_EXPORT_DEPENDS "roscpp" "rospy")
set(testworld_gazebo_BUILDTOOL_DEPENDS "catkin")
set(testworld_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(testworld_gazebo_EXEC_DEPENDS "roscpp" "rospy")
set(testworld_gazebo_RUN_DEPENDS "roscpp" "rospy")
set(testworld_gazebo_TEST_DEPENDS )
set(testworld_gazebo_DOC_DEPENDS )
set(testworld_gazebo_URL_WEBSITE "")
set(testworld_gazebo_URL_BUGTRACKER "")
set(testworld_gazebo_URL_REPOSITORY "")
set(testworld_gazebo_DEPRECATED "")