set(_CATKIN_CURRENT_PACKAGE "master_discovery_fkie")
set(master_discovery_fkie_VERSION "0.8.9")
set(master_discovery_fkie_MAINTAINER "Alexander Tiderko <alexander.tiderko@gmail.com>")
set(master_discovery_fkie_PACKAGE_FORMAT "1")
set(master_discovery_fkie_BUILD_DEPENDS "std_srvs" "multimaster_msgs_fkie")
set(master_discovery_fkie_BUILD_EXPORT_DEPENDS "std_srvs" "multimaster_msgs_fkie" "rospy" "roslib" "rosgraph" "python-avahi" "avahi-daemon")
set(master_discovery_fkie_BUILDTOOL_DEPENDS "catkin")
set(master_discovery_fkie_BUILDTOOL_EXPORT_DEPENDS )
set(master_discovery_fkie_EXEC_DEPENDS "std_srvs" "multimaster_msgs_fkie" "rospy" "roslib" "rosgraph" "python-avahi" "avahi-daemon")
set(master_discovery_fkie_RUN_DEPENDS "std_srvs" "multimaster_msgs_fkie" "rospy" "roslib" "rosgraph" "python-avahi" "avahi-daemon")
set(master_discovery_fkie_TEST_DEPENDS )
set(master_discovery_fkie_DOC_DEPENDS )
set(master_discovery_fkie_URL_WEBSITE "http://ros.org/wiki/master_discovery_fkie")
set(master_discovery_fkie_URL_BUGTRACKER "")
set(master_discovery_fkie_URL_REPOSITORY "")
set(master_discovery_fkie_DEPRECATED "")