set(_CATKIN_CURRENT_PACKAGE "multimaster_msgs_fkie")
set(multimaster_msgs_fkie_VERSION "0.8.9")
set(multimaster_msgs_fkie_MAINTAINER "Alexander Tiderko <alexander.tiderko@gmail.com>")
set(multimaster_msgs_fkie_PACKAGE_FORMAT "1")
set(multimaster_msgs_fkie_BUILD_DEPENDS "message_generation" "std_msgs")
set(multimaster_msgs_fkie_BUILD_EXPORT_DEPENDS "message_runtime" "std_msgs")
set(multimaster_msgs_fkie_BUILDTOOL_DEPENDS "catkin")
set(multimaster_msgs_fkie_BUILDTOOL_EXPORT_DEPENDS )
set(multimaster_msgs_fkie_EXEC_DEPENDS "message_runtime" "std_msgs")
set(multimaster_msgs_fkie_RUN_DEPENDS "message_runtime" "std_msgs")
set(multimaster_msgs_fkie_TEST_DEPENDS )
set(multimaster_msgs_fkie_DOC_DEPENDS )
set(multimaster_msgs_fkie_URL_WEBSITE "http://ros.org/wiki/multimaster_msgs_fkie")
set(multimaster_msgs_fkie_URL_BUGTRACKER "")
set(multimaster_msgs_fkie_URL_REPOSITORY "")
set(multimaster_msgs_fkie_DEPRECATED "")