set(_CATKIN_CURRENT_PACKAGE "pose_follower")
set(pose_follower_VERSION "0.2.0")
set(pose_follower_MAINTAINER "Martin Günther <martin.guenther@dfki.de>")
set(pose_follower_PACKAGE_FORMAT "2")
set(pose_follower_BUILD_DEPENDS "base_local_planner" "costmap_2d" "nav_core" "nav_msgs" "pluginlib" "roscpp" "tf")
set(pose_follower_BUILD_EXPORT_DEPENDS "base_local_planner" "costmap_2d" "nav_core" "nav_msgs" "pluginlib" "roscpp" "tf")
set(pose_follower_BUILDTOOL_DEPENDS "catkin")
set(pose_follower_BUILDTOOL_EXPORT_DEPENDS )
set(pose_follower_EXEC_DEPENDS "base_local_planner" "costmap_2d" "nav_core" "nav_msgs" "pluginlib" "roscpp" "tf")
set(pose_follower_RUN_DEPENDS "base_local_planner" "costmap_2d" "nav_core" "nav_msgs" "pluginlib" "roscpp" "tf")
set(pose_follower_TEST_DEPENDS )
set(pose_follower_DOC_DEPENDS )
set(pose_follower_URL_WEBSITE "http://wiki.ros.org/pose_follower")
set(pose_follower_URL_BUGTRACKER "https://github.com/ros-planning/navigation_experimental/issues")
set(pose_follower_URL_REPOSITORY "https://github.com/ros-planning/navigation_experimental.git")
set(pose_follower_DEPRECATED "")