set(_CATKIN_CURRENT_PACKAGE "assisted_teleop")
set(assisted_teleop_VERSION "0.2.0")
set(assisted_teleop_MAINTAINER "Martin Günther <martin.guenther@dfki.de>")
set(assisted_teleop_PACKAGE_FORMAT "2")
set(assisted_teleop_BUILD_DEPENDS "actionlib" "angles" "base_local_planner" "costmap_2d" "eigen" "filters" "geometry_msgs" "message_filters" "move_base_msgs" "pluginlib" "roscpp" "roslib" "sensor_msgs" "tf")
set(assisted_teleop_BUILD_EXPORT_DEPENDS "actionlib" "angles" "base_local_planner" "costmap_2d" "eigen" "filters" "geometry_msgs" "message_filters" "move_base_msgs" "pluginlib" "roscpp" "roslib" "sensor_msgs" "tf")
set(assisted_teleop_BUILDTOOL_DEPENDS "catkin")
set(assisted_teleop_BUILDTOOL_EXPORT_DEPENDS )
set(assisted_teleop_EXEC_DEPENDS "actionlib" "angles" "base_local_planner" "costmap_2d" "eigen" "filters" "geometry_msgs" "message_filters" "move_base_msgs" "pluginlib" "roscpp" "roslib" "sensor_msgs" "tf")
set(assisted_teleop_RUN_DEPENDS "actionlib" "angles" "base_local_planner" "costmap_2d" "eigen" "filters" "geometry_msgs" "message_filters" "move_base_msgs" "pluginlib" "roscpp" "roslib" "sensor_msgs" "tf")
set(assisted_teleop_TEST_DEPENDS )
set(assisted_teleop_DOC_DEPENDS )
set(assisted_teleop_URL_WEBSITE "http://wiki.ros.org/assisted_teleop")
set(assisted_teleop_URL_BUGTRACKER "https://github.com/ros-planning/navigation_experimental/issues")
set(assisted_teleop_URL_REPOSITORY "https://github.com/ros-planning/navigation_experimental.git")
set(assisted_teleop_DEPRECATED "")