set(_CATKIN_CURRENT_PACKAGE "goal_passer")
set(goal_passer_VERSION "0.2.0")
set(goal_passer_MAINTAINER "Martin Günther <martin.guenther@dfki.de>")
set(goal_passer_PACKAGE_FORMAT "2")
set(goal_passer_BUILD_DEPENDS "costmap_2d" "nav_core" "pluginlib" "roscpp")
set(goal_passer_BUILD_EXPORT_DEPENDS "costmap_2d" "nav_core" "pluginlib" "roscpp")
set(goal_passer_BUILDTOOL_DEPENDS "catkin")
set(goal_passer_BUILDTOOL_EXPORT_DEPENDS )
set(goal_passer_EXEC_DEPENDS "costmap_2d" "nav_core" "pluginlib" "roscpp")
set(goal_passer_RUN_DEPENDS "costmap_2d" "nav_core" "pluginlib" "roscpp")
set(goal_passer_TEST_DEPENDS )
set(goal_passer_DOC_DEPENDS )
set(goal_passer_URL_WEBSITE "http://wiki.ros.org/goal_passer")
set(goal_passer_URL_BUGTRACKER "https://github.com/ros-planning/navigation_experimental/issues")
set(goal_passer_URL_REPOSITORY "https://github.com/ros-planning/navigation_experimental.git")
set(goal_passer_DEPRECATED "")