set(_CATKIN_CURRENT_PACKAGE "octomap_server")
set(octomap_server_VERSION "0.6.1")
set(octomap_server_MAINTAINER "Armin Hornung <armin@hornung.io>")
set(octomap_server_PACKAGE_FORMAT "1")
set(octomap_server_BUILD_DEPENDS "roscpp" "visualization_msgs" "sensor_msgs" "pcl_ros" "pcl_conversions" "nav_msgs" "std_msgs" "std_srvs" "octomap" "octomap_msgs" "octomap_ros" "dynamic_reconfigure" "nodelet" "libpcl-all-dev")
set(octomap_server_BUILD_EXPORT_DEPENDS "roscpp" "visualization_msgs" "sensor_msgs" "pcl_ros" "pcl_conversions" "nav_msgs" "std_msgs" "std_srvs" "octomap" "octomap_msgs" "octomap_ros" "dynamic_reconfigure" "nodelet" "libpcl-all")
set(octomap_server_BUILDTOOL_DEPENDS "catkin")
set(octomap_server_BUILDTOOL_EXPORT_DEPENDS )
set(octomap_server_EXEC_DEPENDS "roscpp" "visualization_msgs" "sensor_msgs" "pcl_ros" "pcl_conversions" "nav_msgs" "std_msgs" "std_srvs" "octomap" "octomap_msgs" "octomap_ros" "dynamic_reconfigure" "nodelet" "libpcl-all")
set(octomap_server_RUN_DEPENDS "roscpp" "visualization_msgs" "sensor_msgs" "pcl_ros" "pcl_conversions" "nav_msgs" "std_msgs" "std_srvs" "octomap" "octomap_msgs" "octomap_ros" "dynamic_reconfigure" "nodelet" "libpcl-all")
set(octomap_server_TEST_DEPENDS )
set(octomap_server_DOC_DEPENDS )
set(octomap_server_URL_WEBSITE "http://www.ros.org/wiki/octomap_server")
set(octomap_server_URL_BUGTRACKER "https://github.com/OctoMap/octomap_mapping/issues")
set(octomap_server_URL_REPOSITORY "https://github.com/OctoMap/octomap_mapping")
set(octomap_server_DEPRECATED "")