set(_CATKIN_CURRENT_PACKAGE "sbpl_recovery")
set(sbpl_recovery_VERSION "0.2.0")
set(sbpl_recovery_MAINTAINER "Martin Günther <martin.guenther@dfki.de>")
set(sbpl_recovery_PACKAGE_FORMAT "2")
set(sbpl_recovery_BUILD_DEPENDS "base_local_planner" "costmap_2d" "nav_core" "pluginlib" "pose_follower" "roscpp" "sbpl_lattice_planner")
set(sbpl_recovery_BUILD_EXPORT_DEPENDS "base_local_planner" "costmap_2d" "nav_core" "pluginlib" "pose_follower" "roscpp" "sbpl_lattice_planner")
set(sbpl_recovery_BUILDTOOL_DEPENDS "catkin")
set(sbpl_recovery_BUILDTOOL_EXPORT_DEPENDS )
set(sbpl_recovery_EXEC_DEPENDS "base_local_planner" "costmap_2d" "nav_core" "pluginlib" "pose_follower" "roscpp" "sbpl_lattice_planner")
set(sbpl_recovery_RUN_DEPENDS "base_local_planner" "costmap_2d" "nav_core" "pluginlib" "pose_follower" "roscpp" "sbpl_lattice_planner")
set(sbpl_recovery_TEST_DEPENDS )
set(sbpl_recovery_DOC_DEPENDS )
set(sbpl_recovery_URL_WEBSITE "http://wiki.ros.org/sbpl_recovery")
set(sbpl_recovery_URL_BUGTRACKER "https://github.com/ros-planning/navigation_experimental/issues")
set(sbpl_recovery_URL_REPOSITORY "https://github.com/ros-planning/navigation_experimental.git")
set(sbpl_recovery_DEPRECATED "")