set(_CATKIN_CURRENT_PACKAGE "twist_recovery")
set(twist_recovery_VERSION "0.2.0")
set(twist_recovery_MAINTAINER "Martin Günther <martin.guenther@dfki.de>")
set(twist_recovery_PACKAGE_FORMAT "2")
set(twist_recovery_BUILD_DEPENDS "base_local_planner" "costmap_2d" "geometry_msgs" "nav_core" "pluginlib")
set(twist_recovery_BUILD_EXPORT_DEPENDS "base_local_planner" "costmap_2d" "geometry_msgs" "nav_core" "pluginlib")
set(twist_recovery_BUILDTOOL_DEPENDS "catkin")
set(twist_recovery_BUILDTOOL_EXPORT_DEPENDS )
set(twist_recovery_EXEC_DEPENDS "base_local_planner" "costmap_2d" "geometry_msgs" "nav_core" "pluginlib")
set(twist_recovery_RUN_DEPENDS "base_local_planner" "costmap_2d" "geometry_msgs" "nav_core" "pluginlib")
set(twist_recovery_TEST_DEPENDS )
set(twist_recovery_DOC_DEPENDS )
set(twist_recovery_URL_WEBSITE "http://wiki.ros.org/twist_recovery")
set(twist_recovery_URL_BUGTRACKER "https://github.com/ros-planning/navigation_experimental/issues")
set(twist_recovery_URL_REPOSITORY "https://github.com/ros-planning/navigation_experimental.git")
set(twist_recovery_DEPRECATED "")