set(_CATKIN_CURRENT_PACKAGE "my_robot_navigation")
set(my_robot_navigation_VERSION "0.0.0")
set(my_robot_navigation_MAINTAINER "imesh <imesh@todo.todo>")
set(my_robot_navigation_PACKAGE_FORMAT "2")
set(my_robot_navigation_BUILD_DEPENDS )
set(my_robot_navigation_BUILD_EXPORT_DEPENDS )
set(my_robot_navigation_BUILDTOOL_DEPENDS "catkin")
set(my_robot_navigation_BUILDTOOL_EXPORT_DEPENDS )
set(my_robot_navigation_EXEC_DEPENDS )
set(my_robot_navigation_RUN_DEPENDS )
set(my_robot_navigation_TEST_DEPENDS )
set(my_robot_navigation_DOC_DEPENDS )
set(my_robot_navigation_URL_WEBSITE "")
set(my_robot_navigation_URL_BUGTRACKER "")
set(my_robot_navigation_URL_REPOSITORY "")
set(my_robot_navigation_DEPRECATED "")